export const COMPLIANCE_FRAMEWORK = {
  HIPAA: "HIPAA",
  GDPR: "GDPR",
  CCPA: "CCPA",
  CUSTOM: "CUSTOM",
} as const;

export type ComplianceFramework =
  (typeof COMPLIANCE_FRAMEWORK)[keyof typeof COMPLIANCE_FRAMEWORK];

export interface ComplianceFrameworkOption {
  id: ComplianceFramework;
  labelKey: string;
  descriptionKey: string;
  entityCount?: number;
}

export const DETECTABLE_ENTITY_TYPE = {
  PERSON: "PERSON",
  LOCATION: "LOCATION",
  ORGANIZATION: "ORGANIZATION",
  DATE: "DATE",
  TIME: "TIME",
  DATE_TIME: "DATE_TIME",
  EMAIL_ADDRESS: "EMAIL_ADDRESS",
  PHONE_NUMBER: "PHONE_NUMBER",
  FAX: "FAX",
  ID_NUMBER: "ID_NUMBER",
  NATIONAL_ID: "NATIONAL_ID",
  PASSPORT: "PASSPORT",
  SSN: "SSN",
  CREDIT_CARD: "CREDIT_CARD",
  BANK_ACCOUNT: "BANK_ACCOUNT",
  ACCOUNT_NUMBER: "ACCOUNT_NUMBER",
  HEALTH_PLAN_BENEFICIARY_NUMBER: "HEALTH_PLAN_BENEFICIARY_NUMBER",
  CERTIFICATE_NUMBER: "CERTIFICATE_NUMBER",
  VEHICLE_ID: "VEHICLE_ID",
  DEVICE_ID: "DEVICE_ID",
  URL: "URL",
  IP_ADDRESS: "IP_ADDRESS",
  MEDICAL_RECORD_NUMBER: "MEDICAL_RECORD_NUMBER",
  MEDICAL_RECORD: "MEDICAL_RECORD",
  BIOMETRIC_ID: "BIOMETRIC_ID",
  BIOLOGICAL_DATA: "BIOLOGICAL_DATA",
  PHOTO_IMAGE: "PHOTO_IMAGE",
  FULL_FACE_PHOTO: "FULL_FACE_PHOTO",
  FREE_TEXT: "FREE_TEXT",
  GEOPOINT: "GEOPOINT",
  AGE: "AGE",
  UNIQUE_IDENTIFIER: "UNIQUE_IDENTIFIER",
} as const;

export type DetectableEntityType =
  (typeof DETECTABLE_ENTITY_TYPE)[keyof typeof DETECTABLE_ENTITY_TYPE];

// GDPR policy below also covers UK DPI and Swiss FADP as risk-based frameworks.
export const COMPLIANCE_FRAMEWORK_ENTITY_TYPES: Record<
  ComplianceFramework,
  ReadonlyArray<DetectableEntityType>
> = {
  [COMPLIANCE_FRAMEWORK.GDPR]: [
    DETECTABLE_ENTITY_TYPE.PERSON,
    DETECTABLE_ENTITY_TYPE.LOCATION,
    DETECTABLE_ENTITY_TYPE.ORGANIZATION,
    DETECTABLE_ENTITY_TYPE.DATE,
    DETECTABLE_ENTITY_TYPE.TIME,
    DETECTABLE_ENTITY_TYPE.DATE_TIME,
    DETECTABLE_ENTITY_TYPE.EMAIL_ADDRESS,
    DETECTABLE_ENTITY_TYPE.PHONE_NUMBER,
    DETECTABLE_ENTITY_TYPE.ID_NUMBER,
    DETECTABLE_ENTITY_TYPE.NATIONAL_ID,
    DETECTABLE_ENTITY_TYPE.PASSPORT,
    DETECTABLE_ENTITY_TYPE.CREDIT_CARD,
    DETECTABLE_ENTITY_TYPE.BANK_ACCOUNT,
    DETECTABLE_ENTITY_TYPE.IP_ADDRESS,
    DETECTABLE_ENTITY_TYPE.DEVICE_ID,
    DETECTABLE_ENTITY_TYPE.MEDICAL_RECORD_NUMBER,
    DETECTABLE_ENTITY_TYPE.BIOLOGICAL_DATA,
    DETECTABLE_ENTITY_TYPE.PHOTO_IMAGE,
    DETECTABLE_ENTITY_TYPE.FREE_TEXT,
    DETECTABLE_ENTITY_TYPE.GEOPOINT,
  ],
  [COMPLIANCE_FRAMEWORK.HIPAA]: [
    DETECTABLE_ENTITY_TYPE.PERSON,
    DETECTABLE_ENTITY_TYPE.LOCATION,
    DETECTABLE_ENTITY_TYPE.ORGANIZATION,
    DETECTABLE_ENTITY_TYPE.DATE,
    DETECTABLE_ENTITY_TYPE.TIME,
    DETECTABLE_ENTITY_TYPE.DATE_TIME,
    DETECTABLE_ENTITY_TYPE.PHONE_NUMBER,
    DETECTABLE_ENTITY_TYPE.FAX,
    DETECTABLE_ENTITY_TYPE.EMAIL_ADDRESS,
    DETECTABLE_ENTITY_TYPE.SSN,
    DETECTABLE_ENTITY_TYPE.MEDICAL_RECORD_NUMBER,
    DETECTABLE_ENTITY_TYPE.HEALTH_PLAN_BENEFICIARY_NUMBER,
    DETECTABLE_ENTITY_TYPE.ACCOUNT_NUMBER,
    DETECTABLE_ENTITY_TYPE.CERTIFICATE_NUMBER,
    DETECTABLE_ENTITY_TYPE.VEHICLE_ID,
    DETECTABLE_ENTITY_TYPE.DEVICE_ID,
    DETECTABLE_ENTITY_TYPE.URL,
    DETECTABLE_ENTITY_TYPE.IP_ADDRESS,
    DETECTABLE_ENTITY_TYPE.BIOMETRIC_ID,
    DETECTABLE_ENTITY_TYPE.FULL_FACE_PHOTO,
    DETECTABLE_ENTITY_TYPE.FREE_TEXT,
    DETECTABLE_ENTITY_TYPE.UNIQUE_IDENTIFIER,
  ],
  [COMPLIANCE_FRAMEWORK.CCPA]: [
    DETECTABLE_ENTITY_TYPE.PERSON,
    DETECTABLE_ENTITY_TYPE.LOCATION,
    DETECTABLE_ENTITY_TYPE.EMAIL_ADDRESS,
    DETECTABLE_ENTITY_TYPE.PHONE_NUMBER,
    DETECTABLE_ENTITY_TYPE.ID_NUMBER,
    DETECTABLE_ENTITY_TYPE.ACCOUNT_NUMBER,
    DETECTABLE_ENTITY_TYPE.CREDIT_CARD,
    DETECTABLE_ENTITY_TYPE.BANK_ACCOUNT,
    DETECTABLE_ENTITY_TYPE.IP_ADDRESS,
    DETECTABLE_ENTITY_TYPE.DEVICE_ID,
    DETECTABLE_ENTITY_TYPE.GEOPOINT,
  ],
  [COMPLIANCE_FRAMEWORK.CUSTOM]: Object.values(DETECTABLE_ENTITY_TYPE),
} as const;

const FRAMEWORK_ENTITY_COUNT: Record<ComplianceFramework, number> = {
  [COMPLIANCE_FRAMEWORK.HIPAA]:
    COMPLIANCE_FRAMEWORK_ENTITY_TYPES[COMPLIANCE_FRAMEWORK.HIPAA].length,
  [COMPLIANCE_FRAMEWORK.GDPR]:
    COMPLIANCE_FRAMEWORK_ENTITY_TYPES[COMPLIANCE_FRAMEWORK.GDPR].length,
  [COMPLIANCE_FRAMEWORK.CCPA]:
    COMPLIANCE_FRAMEWORK_ENTITY_TYPES[COMPLIANCE_FRAMEWORK.CCPA].length,
  [COMPLIANCE_FRAMEWORK.CUSTOM]:
    COMPLIANCE_FRAMEWORK_ENTITY_TYPES[COMPLIANCE_FRAMEWORK.CUSTOM].length,
};

export const COMPLIANCE_FRAMEWORK_OPTIONS: ReadonlyArray<ComplianceFrameworkOption> =
  [
    {
      id: COMPLIANCE_FRAMEWORK.HIPAA,
      labelKey: "compliance.frameworks.hipaa.label",
      descriptionKey: "compliance.frameworks.hipaa.desc",
      entityCount: FRAMEWORK_ENTITY_COUNT[COMPLIANCE_FRAMEWORK.HIPAA],
    },
    {
      id: COMPLIANCE_FRAMEWORK.GDPR,
      labelKey: "compliance.frameworks.gdpr.label",
      descriptionKey: "compliance.frameworks.gdpr.desc",
      entityCount: FRAMEWORK_ENTITY_COUNT[COMPLIANCE_FRAMEWORK.GDPR],
    },
    {
      id: COMPLIANCE_FRAMEWORK.CCPA,
      labelKey: "compliance.frameworks.ccpa.label",
      descriptionKey: "compliance.frameworks.ccpa.desc",
      entityCount: FRAMEWORK_ENTITY_COUNT[COMPLIANCE_FRAMEWORK.CCPA],
    },
    {
      id: COMPLIANCE_FRAMEWORK.CUSTOM,
      labelKey: "compliance.frameworks.custom.label",
      descriptionKey: "compliance.frameworks.custom.desc",
      entityCount: FRAMEWORK_ENTITY_COUNT[COMPLIANCE_FRAMEWORK.CUSTOM],
    },
  ];
